version: "3.5"

services:
  sonarqube:
    container_name: sonarqube
    build: .
    ports:
      - 9000:9000
    volumes:
      - ./sonarqube/conf:/opt/sonarqube/conf
      - ./sonarqube/extensions:/opt/sonarqube/extensions
      - ./sonarqube/logs:/opt/sonarqube/logs
      - ./sonarqube/data:/opt/sonarqube/data
    depends_on:
      - sonarqubedb
    restart: always

  sonarqubedb:
    container_name: sonarqubedb
    image: postgres
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=isyl]y[sonarqube
    volumes:
      - ./postgresql:/var/lib/postgresql
      # This needs explicit mapping due to https://github.com/docker-library/postgres/blob/4e48e3228a30763913ece952c611e5e9b95c8759/Dockerfile.template#L52
      - ./postgresql/data:/var/lib/postgresql/data
    restart: always

  jenkins:
    container_name: jenkins
    build:
      context: ./jenkins-docker
      dockerfile: Dockerfile
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - ./app/data/jenkins_home:/var/jenkins_home
      - ./app/config/executors.groovy:/usr/share/jenkins/ref/init.groovy.d/executors.groovy
    restart: always